package com.example.jobharbor.model

import com.example.jobharbor.R

object FakeJobResource {
    val dummyJobs = listOf(
        Job(
            id = 1,
            logo = R.drawable.logo1,
            bgImg = R.drawable.bg1,
            companyName = "Jasa Kebun Rukun",
            jobTitle = "Penanam Bibit",
            isFavorite = false,
            location = "Subang, Jawa Barat",
            category = listOf( "Pertanian", "Penanaman", "Teliti"),
            salary = "Rp. 1,8Jt/Bulan",
            description = "Menanam bibit tanaman dengan teknik yang tepat, merawat tanaman, dan memastikan pertumbuhan yang sehat.",
            requirements = "Kemampuan dasar dalam penanganan tanaman seperti penanaman, penyiraman, dan pemupukan.",
            companyProfile = "Jasa Kebun Rukun memberikan layanan penanaman dan perawatan tanaman dengan sentuhan keahlian lokal.",
        ),
        Job(
            id = 2,
            logo = R.drawable.logo2,
            bgImg = R.drawable.bg2,
            companyName = "Kreasi Rajut Sederhana",
            jobTitle = "Penjahit Rajutan",
            isFavorite = false,
            location = "Bogor, Jawa Barat",
            category = listOf("Kerajinan Tangan", "Rajutan", "Ulet"),
            salary = "Rp. 1,5Jt/Bulan",
            description = "Membuat rajutan sederhana seperti topi, sarung tangan, atau syal dengan menggunakan benang dan jarum rajut.",
            requirements = " Kemampuan dalam teknik dasar rajutan seperti membuat pola sederhana, mengikat benang, dan merajut, Kemampuan untuk menghasilkan desain rajutan yang menarik dan kreatif.",
            companyProfile = "Jasa Kebun Rukun memberikan layanan penanaman dan perawatan tanaman dengan sentuhan keahlian lokal.",
        ),
        Job(
            id = 3,
            logo = R.drawable.logo3,
            bgImg = R.drawable.bg3,
            companyName = "Toko Sederhana Anak-Anak",
            jobTitle = "Penjaga Toko",
            isFavorite = false,
            location = "Banjar, Jawa Barat",
            category = listOf("Penjualan", "Layanan Pelanggan", "Manajemen Toko"),
            salary = "Rp. 1,5Jt/Bulan",
            description = "Mengelola toko, membantu pelanggan, menjaga kebersihan toko, dan merapihkan barang dagangan.",
            requirements = "Keterampilan dasar dalam melayani pelanggan dan menjaga kebersihan toko.",
            companyProfile = "Toko Sederhana Anak-Anak menyediakan mainan dan peralatan anak-anak dengan harga terjangkau.",
        ),
        Job(
            id = 4,
            logo = R.drawable.logo4,
            bgImg = R.drawable.bg4,
            companyName = "Karya Keramik Asli",
            jobTitle = "Pematung Tanah Liat",
            isFavorite = false,
            location = "Cirebon, Jawa Barat",
            category = listOf("Kerajinan Tangan", "Seni", "Pematung"),
            salary = "Rp. 1,65Jt/Bulan",
            description = "Mengelola toko, membantu pelanggan, menjaga kebersihan toko, dan merapihkan barang dagangan.",
            requirements = "Kemampuan untuk membentuk tanah liat menjadi bentuk yang diinginkan,  Kemampuan untuk menciptakan karya seni yang unik dan menarik dari tanah liat.",
            companyProfile = "Karya Keramik Asli menghadirkan seni keramik unik dengan sentuhan lokal Cirebon.",
        ),
        Job(
            id = 5,
            logo = R.drawable.logo5,
            bgImg = R.drawable.bg5,
            companyName = "Layanan Taman Kreatif",
            jobTitle = "Tukang Kebun",
            isFavorite = false,
            location = "Cirebon, Jawa Barat",
            category = listOf("Perawatan Taman", "Kebun", "Teliti"),
            salary = "Rp. 1,65Jt/Bulan",
            description = "Merawat taman, memangkas tanaman, dan membersihkan area taman.",
            requirements = "Pemahaman dasar tentang taman, alat kebun sederhana, dan ketelitian dalam merawat tanaman.",
            companyProfile = "Layanan Taman Kreatif menyediakan jasa perawatan taman dengan sentuhan kreatif.",
        ),
        Job(
            id = 6,
            logo = R.drawable.logo6,
            bgImg = R.drawable.bg6,
            companyName = "Karya Anyaman Tradisional",
            jobTitle = "Pengrajin Anyaman",
            isFavorite = false,
            location = "Banjar, Jawa Barat",
            category = listOf("Kerajinan Tangan", "Anyaman", "Keterampilan"),
            salary = "Rp. 1,7Jt/Bulan",
            description = "Membuat anyaman seperti keranjang atau tikar dengan menggunakan bahan alam seperti bambu atau rotan.",
            requirements = "emampuan dasar dalam membuat pola anyaman dan teknik menganyam yang sederhana.",
            companyProfile = "Karya Anyaman Tradisional menghasilkan produk anyaman dengan keindahan desain tradisional Jawa Barat.",
        ),
        Job(
            id = 7,
            logo = R.drawable.logo7,
            bgImg = R.drawable.bg7,
            companyName = "Kue Tradisional Lezat",
            jobTitle = "Penjual Kue Keliling",
            isFavorite = false,
            location = "Cimahi, Jawa Barat",
            category = listOf("Kerajinan Tangan", "Anyaman", "Keterampilan"),
            salary = "Rp. 1,2Jt/Bulan",
            description = "Menjual kue tradisional dengan cara keliling ke berbagai tempat atau di pasar tradisional.",
            requirements = "emampuan dasar dalam membuat pola anyaman dan teknik menganyam yang sederhana.",
            companyProfile = "Kue Tradisional Lezat menyajikan kue-kue tradisional dengan cita rasa khas Jawa Barat.",
        ),
        Job(
            id = 8,
            logo = R.drawable.logo8,
            bgImg = R.drawable.bg8,
            companyName = " Layanan Bersih Mantap",
            jobTitle = "Penyapu Jalanan",
            isFavorite = false,
            location = "Cimahi, Jawa Barat",
            category = listOf("Kerajinan Tangan", "Anyaman", "Keterampilan"),
            salary = "Rp. 1,3Jt/Bulan",
            description = "Membersihkan jalanan, trotoar, dan area publik lainnya menggunakan peralatan kebersihan sederhana.",
            requirements = "Keuletan dan kegigihan dalam bekerja di luar ruangan dan menjaga kebersihan lingkungan.",
            companyProfile = "Layanan Bersih Mantap menyediakan tenaga kerja untuk menjaga kebersihan lingkungan.",
        ),
        Job(
            id = 9,
            logo = R.drawable.logo10,
            bgImg = R.drawable.bg9,
            companyName = "Nasi Goreng Mantap",
            jobTitle = "Asisten Masak",
            isFavorite = false,
            location = "Bandung, Jawa Barat",
            category = listOf("Teliti", "Bekerja keras", "Keterampilan"),
            salary = "Rp. 1,3Jt/Bulan",
            description = "Membantu dalam proses memasak nasi goreng, mempersiapkan bahan, dan merapikan dapur setelah penggunaan.",
            requirements = "Keterampilan dasar memasak, keuletan, dan kecepatan dalam bekerja di dapur.",
            companyProfile = "Nasi Goreng Mantap menyajikan nasi goreng dengan berbagai variasi rasa yang menggugah selera.",
        ),
        Job(
            id = 10,
            logo = R.drawable.logo11,
            bgImg = R.drawable.bg10,
            companyName = "Layanan Cuci Mobil Kilat",
            jobTitle = "Penyedia Jasa Cuci Mobil",
            isFavorite = false,
            location = "Bandung, Jawa Barat",
            category = listOf("Teliti", "Ulet", "Bekerja Keras"),
            salary = "Rp. 1,4Jt/Bulan",
            description = "Membersihkan mobil secara cepat dan menyeluruh, baik bagian luar maupun dalam mobil.",
            requirements = "Keuletan, ketelitian, dan kecepatan dalam memberikan layanan cuci mobil yang bersih dan kilat.",
            companyProfile = "Layanan Cuci Mobil Kilat memberikan layanan cuci mobil dengan hasil yang bersih dan kilat.",
        ),
    )
}